version: "3"

services:

  # Соответственно тут логин и пароль guest/guest
  message_brocker:
    build: MessageBrocker/
    ports:
      - 8081:15672
      - 5672:5672

  python_logick:
    build: Python/
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - "message_brocker"
      - "mongo"
    ports:
      - 8000:8000

  db_sql:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  java_def:
    build: wildfly/
    links:
      - "message_brocker"
      - "mongo"
    ports:
      - 8082:8080
      - 9990:9990

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admine
      MONGO_INITDB_ROOT_PASSWORD: admine

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admine
      ME_CONFIG_MONGODB_ADMINPASSWORD: admine

  